---
development:
  cloud_name: djbskjkn3
  api_key: '444275744743893'
  api_secret: _wYHfRh0otUnt33AI9teGen_pbM
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: djbskjkn3
  api_key: '444275744743893'
  api_secret: _wYHfRh0otUnt33AI9teGen_pbM
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: djbskjkn3
  api_key: '444275744743893'
  api_secret: _wYHfRh0otUnt33AI9teGen_pbM
  enhance_image_tag: true
  static_file_support: false
